use_frameworks!

target 'NLService_Example' do
  pod 'NLService', :path => '../'
  
  target 'NLService_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
